---
- hosts: all
  become: true
  vars :
    create_containers: 1
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1d

   
  tasks:
    - name: Install pip
      apt: name=python-pip state=present
      
    - name: install docker-py
      pip: name=docker-py

    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes 

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates','software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
 
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present     

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present
        
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
   
    - name: docker build image
      command: docker build -t flask-tutorial:latest .
   
    - name: docker run image
      command: docker run -d -p 80:5000 flask-tutorial
